{
  "language": "python",
  "python": [
    "3.7.8"
  ],
  "services": [
    "postgresql"
  ],


  "env": [
    "DJANGO=2.2.1"
  ],
  "before_install": [
    "export DJANGO_SETTINGS_MODULE=vtcvlp.settings",
    "export PYTHONPATH=/home/travis/build/mbambadev/vtc-vlp",
    "export PIP_USE_MIRRORS=true",
    "export BUILD_ON_TRAVIS=true"
  ],
  "install": [
    "pip install -r requirements.txt",
    "pip install django==$DJANGO --quiet",
    "pip install psycopg2 --quiet"
  ],
  "before_script": [
    "psql -c \"CREATE DATABASE vtcdb;\" -U postgres",
    "psql -c \"CREATE USER vtcuser PASSWORD 'vtcpass';\" -U postgres",
    "psql -c \"ALTER USER vtcuser CREATEDB;\" -U postgres",
    "psql -c \"GRANT ALL PRIVILEGES on DATABASE vtcdb to vtcuser;\" -U postgres",
    "export DISPLAY=:99.0",
  ],
  "script": [
    "python manage.py migrate",
    "python manage.py collectstatic --noinput",
    "python manage.py test"
  ]
}