# Generated by Django 2.2 on 2020-09-10 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name of video')),
                ('link', models.URLField(verbose_name='Link of the video')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
            ],
            options={
                'verbose_name': 'Video Link',
                'verbose_name_plural': 'Videos links',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='Member')),
            ],
            options={
                'verbose_name': 'VTC member',
                'verbose_name_plural': 'VTC member',
            },
        ),
    ]
